### PR TITLE
Pass text nodes as props

### PR DESCRIPTION
**Pull request by guangyu-nb**
1. allow text node to be passed in as children prop
2. allow cover text
3. add semantic class names to child nods

### CODE REVIEW

**Review by nb-david — CHANGES_REQUESTED** [review]
Is the "Tap to add" text going to be styled in this component? or will that be handled by whoever is using it.

**Comment by guangyu-nb** [comment]
What do you think? I assume whoever is providing the text will be responsible for styling it, but we can provide some simply styles, such as font and center alignment

**Comment by nb-david** [comment]
If we are providing a prop for it, I think the component should have some responsibility.  Your suggestion of a simple font and center alignment should suffice

**Comment by guangyu-nb** [comment]
Default styling provided

**Review by nb-david — APPROVED** [review]
ok. will publish in a bit

**Pull request merged**
